name: Continuous Delivery

on:
  workflow_dispatch:

jobs:
  infra:
    uses: ./.github/workflows/infra.yml
    permissions:
      contents: read
      security-events: write
    secrets: inherit

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: infra
    secrets: inherit
    with:
      instance_public_ip: ${{ needs.infra.outputs.instance_public_ip }}
